# Wiki Update Tracker, to track changes in wiki original pages, and update issues to report when a translation is required

name: Wiki Update Tracker

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get custom App JWT
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Check original pages status and update issues
        uses: Awagi/wiki-update-tracker@v1.0
        with:
          repo-path: $GITHUB_WORKSPACE
          original-path: "wiki"
          ignored-paths: "wiki/LICENSE,wiki/.vuepress"
          translation-paths: "wiki/fr"
          file-suffix: ".md"
          bot-label: "BOT"
          token: ${{ steps.get_token.outputs.app_token }}
          log-level: "DEBUG"
